version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Paris"
    labels:
      - "dependencies:ci"
      - "dependencies:github-actions"
      - "dependencies"