name: Test pull-request.yml workflow

on:
  workflow_dispatch:
  push:
    branches:
      - "feat/**"
      - "fix/**"
      - "docs/**"
      - "chore/**"
      - "test/**"
      - "refactor/**"
      - "ci/**"
   
jobs:
  test-pull-request:
    name: Test pull-request.yml workflow
    uses: Nebeto/logistiko/.github/workflows/pull-request.yml@main
    with:
      target: ${{ github.ref_name }}
    secrets:
      github-token: ${{ secrets.LOGISTIKO_GITHUB_TOKEN }}

            