name: Test security.yml workflow

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/security.yml"
      - ".github/workflows/test-security.yml"
   
jobs:
  test-security:
    name: Test security.yml workflow
    uses: Nebeto/logistiko/.github/workflows/security.yml@main
    with:
      working-directory: "frontend-project"
      node-version: "latest"
      scan-mode: "all"
      snyk-organization: ${{ vars.SNYK_ORGANIZATION }}
      snyk-project: ${{ vars.SNYK_PROJECT }}
      target: ${{ github.ref }}
      severity-threshold: "low|medium|high"
      fail-on: "upgradable"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}

            