name: Test security.yml workflow

on:
  push:
    paths:
      - ".github/workflows/security.yml"
      - ".github/workflows/test-security.yml"
        
jobs:
    test-security:
        uses: Nebeto/logistiko/.github/workflows/security.yml@main
        with:
          use-node-version: "latest"
          use-scan-mode: "all"
          use-snyk-organization: ${{ secrets.SNYK_ORGANIZATION }}
          use-snyk-project: "nbt-test-logistiko"
          target: ${{ github.ref }}
          severity-threshold: "low|medium|high|critical"
          fail-on: "upgradable"
        secrets:
          github-token: ${{ GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}

            