name: Test security.yml workflow

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/security.yml"
      - ".github/workflows/test-security.yml"

defaults:
  run:
    working-directory: "/frontend-project"
   
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    name: Checkout code
    steps:
      - id: checkout-code
        name: Initialize code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test-security:
    name: Test security.yml workflow
    uses: Nebeto/logistiko/.github/workflows/security.yml@main
    with:
      node-version: "latest"
      scan-mode: "all"
      snyk-project: ${{ vars.SNYK_PROJECT }}
      target: ${{ github.ref }}
      severity-threshold: "low|medium|high|critical"
      fail-on: "upgradable"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      snyk-organization: ${{ secrets.SNYK_ORGANIZATION }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}

            