name: Test security.yml workflow

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1'
  push:
    paths:
      - ".github/workflows/security.yml"
      - ".github/workflows/test-security.yml"
   
jobs:
  test-security:
    name: Test security.yml workflow
    uses: Nebeto/logistiko/.github/workflows/security.yml@main
    with:
      working-directory: "frontend-project"
      node-version: "latest"
      scan-mode: "all"
      snyk-project: ${{ vars.SNYK_PROJECT }}
      target: ${{ github.ref_name }}
      severity-threshold: "critical"
      fail-on: "all"
    secrets:
      github-token: ${{ secrets.LOGISTIKO_GITHUB_TOKEN }}
      snyk-organization: ${{ secrets.SNYK_ORGANIZATION }}
      snyk-token: ${{ secrets.SNYK_TOKEN }}

            